apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-ipfs-stress
  labels:
    name: go-ipfs
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5001"
    prometheus.io/path: "debug/metrics/prometheus"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: go-ipfs-stress
    spec:
      containers:
      - name: go-ipfs
        #        image: "ipfs/go-ipfs:master"
        image: "controlplane/ipfs-cluster-test:latest"
        imagePullPolicy: Always
        command: ["/usr/local/bin/start_ipfs"]
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
        - containerPort: 5001
          name: "api"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - ipfs id -f "<addrs>" | grep -E '/ip4/(172\.31|10)\.'
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
